### PR TITLE
Add hover animation

### PR DESCRIPTION
**Pull request by yang-wei**
Please note that instead of setting `color` as state, I add another state `strokeWidth` to help animating. Also I use `shouldComponentUpdate` to decide if they should do the animation. Feel free to correct me if you think there is another better way ( or you prefer your approach stated in #28 ). I din't any test for the animation since we don't have test spies. If you think adding test for animation is necessary, I will try to add them by adding dependency like `sinon.js`. 

If you're cool with this kind of approach, I will add animation for other charts on this branch too. :bar_chart: :chart_with_upwards_trend:

### CODE REVIEW

**Comment by esbullington** [comment]
Hey @yang-wei thanks for the PR!  Sorry for not getting back earlier -- it's been a busy day.

So, I looked the code, and I describe a few issues below:

1) You wrote "...I use shouldComponentUpdate to decide if they should do the animation."  The problem with this approach will come up when we need to update properties in the `Circle` component, like when we do data frame animations.  If `hoverAnimation` is set to `false`, then no updates will work in the Circle component, because `shouldComponentUpdate` will always return false.  I'd recommend doing something like the approach in #28, which is to use a ternary expression when setting the event handler:

`onMouseOver={this.hoverAnimation ? this.animateCircle : null}`

Alternately, you could render different versions of the circle element depending on whether or not hoverAnimation is true or false, with one version setting the mouse event handlers, and the other without the handlers.

2) Little spelling error: `restroreCircle` -> `restoreCircle`

3) So regarding tests, it's actually pretty cool because React TestUtils lets us do things like simulate events on the virtual DOM.  So I can test your mouseover animation by doing this:

```
    var scatterchart = TestUtils.renderIntoDocument(
      <ScatterChart pointRadius={pointRadius} data={data} width={400} height={200} />
    );
    var circles = TestUtils.scryRenderedDOMComponentsWithTag(
      scatterchart, 'circle');
    var circleOne = circles[0];
    expect(circleOne.getDOMNode().r.baseVal.value).to.equal(pointRadius);
    TestUtils.Simulate.mouseOver(circleOne);
    var newPointRadius = pointRadius * (5 / 4);
    expect(circleOne.getDOMNode().r.baseVal.value).to.equal(newPointRadius);
```

So it would be great if you could add that to the scatterchart-tests.js file to test this addition.

4) Regarding the actual mouseover animation, I like the effect.  It's subtle, which is a good thing here.  I think you could also do something like darken/lighten the color by a certain percentage.  This would be easy in Less or SASS, but here we must [do it in Javascript](http://stackoverflow.com/a/13542669/1002047).

But this is not critical for now -- we can make this change later.

5) There's one more issue to address, which is how to detect nearby mouseevents.  RIght now, it only fires when the mouse is *right* over circle.  Ideally, we'd do something like MetricGraphics does [here](http://metricsgraphicsjs.org/examples.htm) (see "scatterplots" at bottom of page).  A common approach to detect nearby mouseover events is to use a [Voronoi-tessellated](http://bl.ocks.org/mbostock/8027835) overlay, in this case an svg `rect` overlay.  Using Voronoi tessellation is how most scatter charts I've seen pick up mouseover events that are not directly on top of the circles, but nearby.

However, this is not a huge issue, and I don't want to overwhelm you with feedback.  I'm perfectly happy to merge the PR once tests are added and the `shouldComponentUpdate` issue is changed.

Do you want to discuss this approach above and implement it yourself, or do you want to just add the tests and address the `shouldComponentUpdate` and then let me do it later?

For the other animations for the other charts, it'd be great if you could open an issue before each PR, so we can discuss what the animation approach (I'm open to new ideas, just would be good to discuss them first).

Thanks again for the PR -- I look forward to merging it.

**Comment by yang-wei** [comment]
1), 2), 3) should be done =) Really thanks for the feedback. I never know that we can do something like this.
```
component.getDOMNode().r.baseVal.value
```

Regarding to issue 4), 5), I am willing to give them a try and send you a pr if everything go smoothly. I must say these 2 features are really a cool addition for animated graph. First of all, I will add them as a method in scatter chart component, if they are reusable(I think they should) then we can used them as mixins later.

Should I open another pull request for these 2 features ?

**Comment by yang-wei** [comment]
Hey @esbullington I added the `shade` method and was trying to add test for the animation (color) but I can't access its `fill` property.
```
var circleOne = circles[0];
    expect(circleOne.getDOMNode().r.baseVal.value);  // get props r value
    expect(circleOne.getDOMNode().fill.baseVal.value); // undefined
```
I also try log the loop of `getDOMNode()` and dint see any value related to fill. 
```
var circleOne = circles[0];
var circleOneColor = circleOne.getDOMNode();
 for(var obj in circleOneColor) {
        console.log(obj);
 }
// Results
LOG: 'systemLanguage'
LOG: 'cx'
LOG: 'className'
LOG: 'requiredFeatures'
LOG: 'farthestViewportElement'
LOG: 'nearestViewportElement'
LOG: 'cy'
LOG: 'style'
LOG: 'transform'
LOG: 'r'
LOG: 'xmllang'
LOG: 'requiredExtensions'
LOG: 'xmlspace'
LOG: 'externalResourcesRequired'
LOG: 'viewportElement'
LOG: 'ownerSVGElement'
LOG: 'id'
...
```
This give me a lot of DOM related properties but not React component properties.
Do you have any idea?

**Comment by esbullington** [comment]
Hey, you can access the fill value using: `circleOne.getDOMNode().getAttribute('fill')`.  Here is a [site](http://www.w3.org/TR/SVGTiny12/attributeTable.html) that gives a brief overview of the SVG Javascript API, and how to access normal attributes using the normal XML interface (as above) vs the special SVG DOM (like `baseVal.value`).

**Comment by yang-wei** [comment]
I found something on the [spec](http://www.w3.org/TR/SVG/shapes.html#DOMInterfaces). SVG  `<circle>` element  only has 3 *readonly* attributes -  `cx`, `cy`, `r`. So I cannot do `getDOMNode().fill.baseVal.value`.

Instead I will just do something like this:
```
var circleOne = circles[0];
    expect(circleOne.props.r);  // get props r value
    expect(circleOne.props.fill); // get props fill value
```
What do you think? Sorry for spamming your feed hahaha

**Comment by yang-wei** [comment]
Thank you. Using `getDOMNode()` is just what I wanted, thanks ! Will change it =)

**Comment by esbullington** [comment]
You can access the fill value using `getDOMNode.getAttribute('fill')` but the method you are using is better.

**Comment by yang-wei** [comment]
:+1:

**Comment by esbullington** [comment]
Let me look over the whole thing again quick but I'm definitely ready to merge.  Looks good!

**Comment by esbullington** [comment]
Thanks, this is great.  Do you want to have a shot at the Voronoi overlay to detect nearby mouse events for the scatter chart?

Also, the same approach (Voronoi) can be used to give the kind of animation [seen in line charts here](http://www.w3.org/TR/SVGTiny12/attributeTable.html), which I think is a nice kind of animation for line charts.

But please let me know if this is a busy time for you.  It can wait, or else I can do it.  You've already done a lot for this upcoming 0.2.0 release.

Thanks again!

**Comment by yang-wei** [comment]
@esbullington I'm willing to look at that on this weekend. Thanks for the example !

**Pull request merged**
