### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### esbullington/react-d3 now has a Chat Room on Gitter

@yang-wei has just created a chat room. You can visit it here: [https://gitter.im/esbullington/react-d3](https://gitter.im/esbullington/react-d3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/esbullington/react-d3?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by yang-wei** [comment]
I think it will be good to add this.

**Comment by esbullington** [comment]
Hey @yang-wei I think it's a very good idea to have a central communications hub.  I was going to just create an IRC channel, but then I thought it would be easier for less technical users if I went with something like Hipchat.  So I already created a react-d3 Hipchat account.  

However, Gitter looks good.  I was skeptical at first because when Gitter was first released, they required all kinds of invasive permissions on your Github account to sign up.  Fortunately, Github has created finer scoped permissions, and Gitter has adopted them.  So now that situation is much improved and I was happy to sign up.

So I'll integrate this Gitter badge, but I'm closely this PR because I'd like to put the badge below the introduction on the README.

By the way, I also created a react-d3 Google Group, so feel free to sign up and I'll approve you.

**Comment by esbullington** [comment]
Hey @yang-wei Added Gitter to README with PR #102

**Comment by yang-wei** [comment]
thats cool !!!
@esbullington

**Pull request closed without merging**
