### PR TITLE
Allows circles to be toggled

### PR DESCRIPTION
**Pull request by frederickfogerty**

### CODE REVIEW

**Comment by esbullington** [comment]
@frederickfogerty if you could remove the redeclaration of the variable on ln. 209 I'll go ahead and merge it.

**Comment by frederickfogerty** [comment]
Yeah, my bad, didn't see this. I'll do this when I get to work.

**Comment by esbullington** [comment]
No prob, I'll merge it whenever you do.

**Comment by esbullington** [comment]
I rebased this one and [merged it](https://github.com/esbullington/react-d3/commit/b70eeaa543b1cf66d329112658581801335a8f33) so I'm closing this PR.  Thanks!

**Pull request closed without merging**
