### PR TITLE
allow string and number propTypes for width/height attributes

### PR DESCRIPTION
**Pull request by igl**
width & height can be strings (as seen here: https://reactiva.github.io/react-d3-website/)

(Is this the correct repo to make PRs? Or are you working on the reactiva org now?)

### CODE REVIEW

**Comment by igl** [comment]
I tried to run the test locally and thought i am missing some global deps but it looks like your master is broken.

**Comment by yang-wei** [comment]
> I tried to run the test locally and thought i am missing some global deps but it looks like your master is broken.

This is a known issue. This will be merged after #277

**Comment by yang-wei** [comment]
> Is this the correct repo to make PRs? Or are you working on the reactiva org now?

@igl Further notification will be do but now it's fine to open your pr here =)

**Comment by MatthewHerbst** [comment]
I think the example website is wrong. Width and height should be numbers only.

**Comment by igl** [comment]
If they are numbers only, how do you differentiate between a percentage and pixel value? Or em/rem etc.

**Comment by MatthewHerbst** [comment]
@igl That's an excellent point! At the moment the code does not support percentages. However, take a look at #274 where that's being talked about. I assume that with that change then yes, strings would be accepted. Above I was just saying where the code is now.

**Pull request closed without merging**
