### PR TITLE
Could be useful to use this. First seen used by atom, and in many other packages since then

### PR DESCRIPTION
**Pull request by frederickfogerty**
https://github.com/atom/atom/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by esbullington** [comment]
I appreciate your PR, but I'm just not a big fan of these emoji in commit messages.  That said, the Atom CONTRIBUTING.md has some excellent points about how to write good commit messages (ones that I don't always live up to, but aspire to). So if you remove the emoji section I'm all for merging this.

By the way, I like how you namespace your branches.  As we start to get more contributors and PRs, it's a good idea.  I'll try to start doing the same.

**Comment by esbullington** [comment]
@frederickfogerty did you want to change this?  Please let me know, otherwise I'll go ahead and close it.

**Comment by frederickfogerty** [comment]
I removed the emojis, so it's up to you whether you merge it or not

**Comment by esbullington** [comment]
@frederickfogerty wow, you removed the emojis but then put one directly in the CONTRIBUTING?

**Pull request closed without merging**
