### PR TITLE
Line chart voronoi

### PR DESCRIPTION
**Pull request by yang-wei**

### CODE REVIEW

**Comment by yang-wei** [comment]
@esbullington Do you think that we need to make hover animation optional ? I just realised that it's not optional in `scatter chart` too.

**Comment by esbullington** [comment]
Yeah, that would be great: `animation={true}`

**Comment by esbullington** [comment]
@yang-wei I added some line animation to this, check it out in the `yang-wei-linechart-variation` branch.  Basically, I animate the lines now in addition to the circles.  I did need to make a small switch to the Voronoi component, which was to make `opacity` = 0, since I needed to put it in the foreground to prevent triggering `mouseout` and `mouseover` events every time I cross a line.

If you like, I'll push it to this branch, add the optional animation props, and we'll merge.

**Comment by yang-wei** [comment]
Oh yeah I din't think of that. Great feature, just push it ! 

One small thing, we might have to change the event name (`animateCircle`) to something more general because we are animating other thing.

**Comment by esbullington** [comment]
Thanks, @yang-wei I'll make these and other changes sometime tomorrow (had a busy weekend).  Thanks for your input on the data format question.

**Comment by esbullington** [comment]
Hey, @yang-wei I merged your branch to one of my feature branches, which I am about to merge.  Nice work!

**Comment by yang-wei** [comment]
:+1:

**Pull request closed without merging**
