### PR TITLE
Added VennDiagram

### PR DESCRIPTION
**Pull request by tyfoo**
Added a `VennDiagram` using [venn.js](https://github.com/benfred/venn.js/) (see http://www.benfrederickson.com/venn-diagrams-with-d3.js/ for more details)

### CODE REVIEW

**Comment by yang-wei** [comment]
This is great but I don't think it's the requirement for most case in building chart. So I would choose to avoid adding another layer of dependency into this library.

Anyway thanks !

**Comment by tyfoo** [comment]
Thanks for the quick feedback. 

I understand. Would you like me to do a version without the venn.js dependency?

**Comment by yang-wei** [comment]
>  understand. Would you like me to do a version without the venn.js dependency?

that would be awesome !

**Comment by tyfoo** [comment]
@yang-wei please see amended commit without the `venn.js` dependency. 

I've taken the functions used from venn.js and put them under `venn.js` folder, including credit to @benfred and the original library / blog post. I hope that is okay.

**Comment by MatthewHerbst** [comment]
@yang-wei I would say based on how much code is copy/pasted from `venn.js`, just use the dependency. There is no reason to duplicate code, and, none of us are going to spend as much time maintaining and improving that code as the original author.

**Pull request closed without merging**
