### PR TITLE
Add .editorconfig and some minor code cleanup

### PR DESCRIPTION
**Pull request by mwhite**
I am implementing horizontal orientation for cartesian charts.  These are ongoing refactorings in service of that.

### CODE REVIEW

**Comment by yang-wei** [comment]
@mwhite code looks good to me but the test is failing. Please fix it and I will merge.

**Comment by mwhite** [comment]
It's a problem with the test. Nodename is expected to be uppercase G but is actually lowercase g in whatever version of PhantomJS is being run.  Not sure when this was introduced.

I was intending to fix it by applying toUppercase() or the like before the comparison, is that okay?

**Comment by yang-wei** [comment]
@mwhite Is it working at your local? I pull your pr and tests are green locally.

**Comment by MatthewHerbst** [comment]
Please remove the `.editorconfig` from this pr. Everyone uses different editors, and this file is not source code.

**Comment by mwhite** [comment]
It's a standard that works with many different editors. http://editorconfig.org/

There is still a bug that needs to be fixed, one of the refactorings was not quite correct.

**Comment by MatthewHerbst** [comment]
@mwhite it doesn't matter. It's not source code, it doesn't belong in the repo. Coding standards can be enforced by documenting them and ensuring them while reviewing PRs.

**Comment by parshap** [comment]
> Please remove the .editorconfig from this pr. Everyone uses different editors, and this file is not source code.

> @mwhite it doesn't matter. It's not source code, it doesn't belong in the repo. Coding standards can be enforced by documenting them and ensuring them while reviewing PRs.

I disagree. Coding standards are best enforced with code. EditorConfig is a great way to help people use the right whitespace settings. `package.json` isn't source code either, but it helps developers have the right versions of dependencies.

**Comment by MatthewHerbst** [comment]
@parshap `package.json` is required to build the source code. EditorConfig is great, but it's not standard. Next I'll put my `.eslint` file is, and someone else will put their `.jshint`, and it gets out of control. There is a reason you never see these types of files in any major application.

**Comment by mwhite** [comment]
I think you will find quite a high percentage of popular projects have .eslintrc and many have .editorconfig.

**Comment by MatthewHerbst** [comment]
The way I see it: if it's not source code or part of the build process, it doesn't belong. Now, I have plenty of projects where I actually run a lint job as part of the build project, and so yeah,I'l have an `.eslintrc` file in there. However, I wouldn't include one in the repo in the hopes that other people might have ESLint installed in their editors that will pick up my file just to enforce standards.

So, if we are going to include style standard files, I think we should include a task as part of the build to enforce those standards. That way we are not liable to each developers local system preferences. That's all I've got to say about this.

**Comment by parshap** [comment]
@MatthewHerbst: That's fair. I think @mwhite is implicitly asking this project to adopt EditorConfig as a standard — not just haphazardly adding his own configuration file.

> So, if we are going to include style standard files, I think we should include a task as part of the build to enforce those standards. That way we are not liable to each developers local system preferences.

That'd be nice. I think `.editorconfig` in itself is useful even without a build task, but I can see your perspective too.

**Comment by parshap** [comment]
Also: The code changes here are good. Let's not get caught up with EditorConfig and throw the baby out with the bathwater.

@yang-wei: Any other changes required to merge this?

**Comment by mwhite** [comment]
I'm adding tests.  Also, I opened a different PR.

**Comment by yang-wei** [comment]
@parshap I am good with these changes.

Just @mwhite now added some commits to #277 so I might need extra time to have a look at it.

**Pull request closed without merging**
