### PR TITLE
Update README with explicit namespace naming examples

### PR DESCRIPTION
**Pull request by phoenixbox**
#### What's this PR do?

Adds explicit examples of how to use the namespace requires for the lib. Why? Because I had to dive into the code to ensure I was using the right naming convention and I would find it quicker and easier to use with explicit README examples

#### Where should the reviewer start?

`README.md`

#### How should this be manually tested?

Ensure the `markdown` is valid format and styled appropriately

#### Any background context you want to provide?

Thanks for making the lib

#### How does this PR make you feel
feels good man

### CODE REVIEW

**Comment by esbullington** [comment]
Hey, thanks for the PR!  However, you shouldn't have to use relative paths to pull in the charts.  If you installed via NPM, you should be able to do:

    var rd3 = require('react-d3');

And then all the charts should be in the `rd3` namespace (or whatever you want to name it).  So:

var BarChart = rd3.BarChart;
var LineChart = rd3.LineChart;

and so on.  Did you have problems with this way?

But if you're wanting to use `master` from the Github repo, you can do:

`npm run build`
`cd build/cjs`
`npm link`

Then go to your project and run `npm link react-d3`.

But I'm trying to keep relatively up to date on the NPM repo, so you should be able to do that.  Please let me know if you had any issues with that approach.

**Comment by phoenixbox** [comment]
@esbullington Oh I totally derped that! I was meant to write:

```
var BarChart = require('react-d3').BarChart;
var LineChart = require('react-d3').LineChart;
var PieChart = require('react-d3').PieChart;
var AreaChart = require('react-d3').AreaChart;
var Treemap = require('react-d3').Treemap;
var ScatterChart = require('react-d3').ScatterChart;
```

hahaha that was dumb. Yeah I basically just want to be able to see the examples and then think "Oh I want that one!" and then copy `var BarChart = require('react-d3').BarChart;`

Ill update.

**Comment by esbullington** [comment]
Thanks for the update.  I'm  going to merge (how could I not with the doggie vacuum picture!), but I may change the example to:
```
var rd3 = require('react-d3');
var BarChart = rd3.BarChart;
var LineChart = rd3.LineChart;
etc.
```

**Comment by esbullington** [comment]
PS: @phoenixbox I realize now what you're talking about: there was no easy way to figure out the actual chart names without looking at the source.  I thought they were listed but your PR was the first to list them in the README by name.  So thanks again for bringing that up!

**Comment by phoenixbox** [comment]
@esbullington yeah no worries!

**Pull request merged**
